# Generated by Django 3.0.4 on 2021-08-22 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=100, verbose_name='アカウント名')),
                ('pw', models.CharField(max_length=100, verbose_name='パスワード')),
                ('tag', models.CharField(max_length=100, verbose_name='タグ')),
                ('likecount', models.IntegerField(verbose_name='いいね数')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
