# Generated by Django 3.0.4 on 2021-08-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='Post_Detail',
        ),
    ]
