# Generated by Django 3.0.4 on 2021-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210822_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_detail',
            name='contributer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
