# Generated by Django 3.0.4 on 2021-08-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_post_detail_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_detail',
            name='contributer',
        ),
    ]
