# Generated by Django 3.0.4 on 2021-11-23 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_post_detail_contributer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='ac_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='アカウント名'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='likecount',
            field=models.IntegerField(blank=True, null=True, verbose_name='いいね数'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='pw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タグ'),
        ),
        migrations.DeleteModel(
            name='Post_Detail',
        ),
    ]
